### ISSUE TITLE
PDFlib GmbH registration

### ISSUE THREAD

**Issue by t-merz** [adobe/pdf-registry#2]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | Plib |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | PDFlib GmbH |
| Address (line 1) | Franziska-Bilek-Weg 9 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | München 80339 |
| Country | Germany |
| Web Site/URL | www.pdflib.com |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Thomas |
| Last Name | Merz |
| Title | Managing Director |
| Email address | tm@pdflib.com |

## Additional Instructions
```
Adobe assigned this prefix to us in 2002:

Subject:  Your PDF prefix has been registered
    Date: Sat, 8 Jun 2002 04:44:26 -0700 (PDT)
   From:  acrodevsup@adobe.com
      To: tm@pdflib.com
      
We would like to register/make it public (under the original registration date :-) )
```

**Comment by lrosenthol** [comment]
Your registration has been moved here.  Thank you for your long time support of PDF and the registry.
