### ISSUE TITLE
NORM prefix 

### ISSUE THREAD

**Issue by romantoda** [adobe/pdf-registry#4]
# Prefix Registration
## Developer Prefix
| Label | Value |
| ------------- | ----------- |
| Developer Prefix (4 letters) | NORM |

## Organization
| Label | Value |
| ------------- | ----------- |
| Entity/Organization Name | Normex s.r.o. |
| Address (line 1) | Sipova 3 |
| Address (line 2) |  |
| City, State, Zip/Postal Code | Nitra 94901 |
| Country | Slovakia |
| Web Site/URL | www.digitaldocuments.org |

## Person
| Label | Value |
| ------------- | ----------- |
| First Name | Roman |
| Last Name | Toda |
| Title | CTO |
| Email address | toda@digitaldocuments.org |

## Additional Instructions
Please make our registration public. Can't find the original e-mail, but from memory we asked for the prefix around 2000

**Comment by lrosenthol** [comment]
I do not find any previous registration, but I am able to make one now.  NORM is now registered to Normex.
